mod daily;
mod date_interface;
mod filter;
mod footer;
mod help;
mod hints;
mod interface_popup;
mod project_interface;
mod scroll;
mod shared;

pub use daily::render_daily_view;
pub use date_interface::render_date_interface;
pub use filter::render_filter_view;
pub use footer::{centered_rect, render_footer};
pub use help::{get_help_total_lines, render_help_content};
pub use hints::{HINT_OVERLAY_HEIGHT, render_hint_overlay};
pub use project_interface::render_project_interface;
pub use scroll::{CursorContext, ensure_selected_visible, set_edit_cursor};
pub use shared::{remove_all_trailing_tags, remove_last_trailing_tag, wrap_text};
