Output ../datepicker.gif

Set Padding 16
Set Width 1600
Set Height 800
Set TypingSpeed 0.2
Set Theme "DoomOne"

Hide
Type "cd ../../.."
Enter
Sleep 0.3s
Type "cargo run docs/examples/src/example_journal.md"
Enter
Sleep 1s
Show

Sleep 2s

Type "\"
Sleep 1.5s

Type "]"
Sleep 1s

Down@300ms 3
Sleep 0.3s
Right@300ms 1
Sleep 0.5s

Enter
Sleep 1s

Enter
Sleep 0.5s

Shift+Tab
Sleep 0.3s
Shift+Tab
Sleep 0.5s

Type "v1.0 public launch!"
Sleep 0.5s
Enter
Sleep 2s

Hide
Type "d"
Sleep 0.3s
