// Registry module - single source of truth for all commands, keybindings, and filter syntax
//
// Data is defined in TOML files and code is generated by build.rs

include!(concat!(env!("OUT_DIR"), "/registry_generated.rs"));
